# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release
on:
  push:
    branches: [ Release ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Code
        uses: actions/checkout@v2
      - name: Set up JDK 11.0.9
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.9
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.Sonarqube_Github_Token }}
          SONAR_TOKEN: ${{ secrets.Sonarqube_Token }}
        run: ./gradlew sonarqube
  Deploy:
    needs: Tests
    environment:
      name: production
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Code
        uses: actions/checkout@v2
      - name: Set up JDK 11.0.9
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.9
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Build JAR
        run: ./gradlew bootJar
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ppyfamilybe'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d91da74556db437ca1f7eece243553be }}
          package: '${{ github.workspace }}/build/libs/*.jar'
      - name: Verifying Application Connectivity
        run: curl -I http://ppyfamilybe.azurewebsites.net/actuator/health -f --retry 10 --retry-delay 10 --connect-timeout 30