# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build, Test, and Sonar
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out Code
      uses: actions/checkout@v2
    - name: Set up JDK 11.0.9
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.9
    - name: Setup Gradle
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: SonarQube
      env:
        GITHUB_TOKEN: ${{ secrets.Sonarqube_Github_Token }}
        SONAR_TOKEN: ${{ secrets.Sonarqube_Token }}
      run: ./gradlew sonarqube